### ISSUE TITLE
Unable to Boot Demo App

### ISSUE THREAD

**Issue by pynchmeister** [dwrtc/dwrtc#133]
My apologies, deleted due to lack of sleep, readability, and so on...

🤖

**Comment by lroellin** [comment]
I assume you could get it to work? Otherwise, feel free to ask :)

Also, if you ran into problems because docs are unclear, this is always something we can easily fix and benefits other people too.

**Comment by pynchmeister** [comment]
A friend of mine got it to work by himself, but that is not exactly the goal.

I'd be happy to help improve the docs for the greater benefit of the public!
