### ISSUE TITLE
TomP2P use public key

### ISSUE THREAD

**Issue by thde** [dwrtc/dwrtc#46]
Use Webcrypto to generate the ID and sign / verify messages.
https://github.com/diafygi/webcrypto-examples#ecdsa---sign

~~https://tomp2p-docs.netlify.com/net/tomp2p/connection/peercreator~~

**Comment by thde** [comment]
It's also possible to use `protectEntry`:  https://gist.github.com/ManfredKarrer/987421470568eed2b17b

**Comment by lroellin** [comment]
Moved to latex
